config/routes.rb
Rails.application.routes.draw do
  resources :search_suggestions
  root "products#index"
  resources :auto_completes do
    get 'search_suggestions'
  end
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/amount.rb
class Amount < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auto_complete.rb
class AutoComplete < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord

  belongs_to :parent_category, class_name: 'Category', optional: true
end

app/models/color.rb
class Color < ApplicationRecord
end

app/models/currency.rb
class Currency < ApplicationRecord
end

app/models/gender.rb
class Gender < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :vendor, optional: true
  belongs_to :user, optional: true
  belongs_to :product, optional: true
  belongs_to :payable_amount, class_name: "Amount", optional: true
  belongs_to :product_color_mapping, optional: true
  belongs_to :product_size_mapping, optional: true
end

app/models/product.rb
class Product < ApplicationRecord

  has_many :product_secondary_titles, dependent: :destroy
  has_many :product_category_mappings
  has_many :categories, through: :product_category_mappings
  has_many :product_color_mappings
  has_many :colors, through: :product_color_mappings
  has_many :product_vendor_mappings
  has_many :vendors, through: :product_vendor_mappings
  has_many :product_size_mappings
  has_many :sizes, through: :product_size_mappings
end

app/models/product_color_mapping.rb
class ProductColorMapping < ApplicationRecord
  belongs_to :product, optional: true
  belongs_to :color, optional: true
end

app/models/product_gender_mapping.rb
class ProductGenderMapping < ApplicationRecord
  belongs_to :product, optional: true
  belongs_to :gender, optional: true
end

app/models/product_size_mapping.rb
class ProductSizeMapping < ApplicationRecord
  belongs_to :product, optional: true
  belongs_to :size, optional: true
end

app/models/product_sku.rb
class ProductSku < ApplicationRecord
  belongs_to :product, optional: true
  belongs_to :product_category_mapping, optional: true
  belongs_to :product_color_mapping, optional: true
  belongs_to :product_vendor_mapping, optional: true
  belongs_to :product_gender_mapping, optional: true
  belongs_to :product_size_mapping, optional: true
  belongs_to :buyer, class_name: "User", optional: true
end

app/models/product_vendor_mapping.rb
class ProductVendorMapping < ApplicationRecord
  belongs_to :product, optional: true
  belongs_to :vendor, optional: true
end

app/models/search_suggestion.rb
class SearchSuggestion < ApplicationRecord
end

app/models/size.rb
class Size < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/models/vendor.rb
class Vendor < ApplicationRecord
end

app/controllers/search_suggestions_controller.rb
class SearchSuggestionsController < ApplicationController
  before_action :set_search_suggestion, only: [:show, :edit, :update, :destroy]

  # GET /search_suggestions
  # GET /search_suggestions.json
  def index
    @search_suggestions = SearchSuggestion.all
  end

  # GET /search_suggestions/1
  # GET /search_suggestions/1.json
  def show
  end

  # GET /search_suggestions/new
  def new
    @search_suggestion = SearchSuggestion.new
  end

  # GET /search_suggestions/1/edit
  def edit
  end

  # POST /search_suggestions
  # POST /search_suggestions.json
  def create
    @search_suggestion = SearchSuggestion.new(search_suggestion_params)

    respond_to do |format|
      if @search_suggestion.save
        format.html { redirect_to @search_suggestion, notice: 'Search suggestion was successfully created.' }
        format.json { render :show, status: :created, location: @search_suggestion }
      else
        format.html { render :new }
        format.json { render json: @search_suggestion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /search_suggestions/1
  # PATCH/PUT /search_suggestions/1.json
  def update
    respond_to do |format|
      if @search_suggestion.update(search_suggestion_params)
        format.html { redirect_to @search_suggestion, notice: 'Search suggestion was successfully updated.' }
        format.json { render :show, status: :ok, location: @search_suggestion }
      else
        format.html { render :edit }
        format.json { render json: @search_suggestion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /search_suggestions/1
  # DELETE /search_suggestions/1.json
  def destroy
    @search_suggestion.destroy
    respond_to do |format|
      format.html { redirect_to search_suggestions_url, notice: 'Search suggestion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_search_suggestion
      @search_suggestion = SearchSuggestion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def search_suggestion_params
      params.fetch(:search_suggestion, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auto_completes_helper.rb
module AutoCompletesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/search_suggestions_helper.rb
module SearchSuggestionsHelper
end

app/views/search_suggestions/_form.html.erb
<%= simple_form_for(@search_suggestion) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/search_suggestions/edit.html.erb
<h1>Editing Search Suggestion</h1>

<%= render 'form', search_suggestion: @search_suggestion %>

<%= link_to 'Show', @search_suggestion %> |
<%= link_to 'Back', search_suggestions_path %>

app/views/search_suggestions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Search Suggestions</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @search_suggestions.each do |search_suggestion| %>
      <tr>
        <td><%= link_to 'Show', search_suggestion %></td>
        <td><%= link_to 'Edit', edit_search_suggestion_path(search_suggestion) %></td>
        <td><%= link_to 'Destroy', search_suggestion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Search Suggestion', new_search_suggestion_path %>

app/views/search_suggestions/new.html.erb
<h1>New Search Suggestion</h1>

<%= render 'form', search_suggestion: @search_suggestion %>

<%= link_to 'Back', search_suggestions_path %>

app/views/search_suggestions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_search_suggestion_path(@search_suggestion) %> |
<%= link_to 'Back', search_suggestions_path %>