config/routes.rb
Rails.application.routes.draw do
  resources :search_suggestions
  root "products#index"
  resources :auto_completes do
    get 'search_suggestions'
  end
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/amount.rb
class Amount < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auto_complete.rb
class AutoComplete < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord

  belongs_to :parent_category, class_name: 'Category', optional: true
end

app/models/color.rb
class Color < ApplicationRecord
end

app/models/currency.rb
class Currency < ApplicationRecord
end

app/models/gender.rb
class Gender < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :vendor, optional: true
  belongs_to :user, optional: true
  belongs_to :product, optional: true
  belongs_to :payable_amount, class_name: "Amount", optional: true
  belongs_to :product_color_mapping, optional: true
  belongs_to :product_size_mapping, optional: true
end

app/models/product.rb
class Product < ApplicationRecord

  has_many :product_secondary_titles, dependent: :destroy
  has_many :product_category_mappings
  has_many :categories, through: :product_category_mappings
  has_many :product_color_mappings
  has_many :colors, through: :product_color_mappings
  has_many :product_vendor_mappings
  has_many :vendors, through: :product_vendor_mappings
  has_many :product_size_mappings
  has_many :sizes, through: :product_size_mappings
end

app/models/product_color_mapping.rb
class ProductColorMapping < ApplicationRecord
  belongs_to :product, optional: true
  belongs_to :color, optional: true
end

app/models/product_gender_mapping.rb
class ProductGenderMapping < ApplicationRecord
  belongs_to :product, optional: true
  belongs_to :gender, optional: true
end

app/models/product_secondary_title.rb
class ProductSecondaryTitle < ApplicationRecord
  belongs_to :product, optional: true
end

app/models/product_size_mapping.rb
class ProductSizeMapping < ApplicationRecord
  belongs_to :product, optional: true
  belongs_to :size, optional: true
end

app/models/product_sku.rb
class ProductSku < ApplicationRecord
  belongs_to :product, optional: true
  belongs_to :product_category_mapping, optional: true
  belongs_to :product_color_mapping, optional: true
  belongs_to :product_vendor_mapping, optional: true
  belongs_to :product_gender_mapping, optional: true
  belongs_to :product_size_mapping, optional: true
  belongs_to :buyer, class_name: "User", optional: true
end

app/models/product_vendor_mapping.rb
class ProductVendorMapping < ApplicationRecord
  belongs_to :product, optional: true
  belongs_to :vendor, optional: true
end

app/models/search_suggestion.rb
class SearchSuggestion < ApplicationRecord
end

app/models/size.rb
class Size < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/models/vendor.rb
class Vendor < ApplicationRecord
end

app/controllers/auto_completes_controller.rb
class AutoCompletesController < ApplicationController
  before_action :set_auto_complete, only: [:show, :edit, :update, :destroy]

  # GET /auto_completes
  # GET /auto_completes.json
  def index
    @auto_completes = AutoComplete.all
    respond_to do |format|
      format.js
    end
    # render json: %w[foo bar]
  end
 
  # GET /auto_completes/1
  # GET /auto_completes/1.json
  def show
  end

  # GET /auto_completes/new
  def new
    @auto_complete = AutoComplete.new
  end

  # GET /auto_completes/1/edit
  def edit
  end

  # POST /auto_completes
  # POST /auto_completes.json
  def create
    @auto_complete = AutoComplete.new(auto_complete_params)

    respond_to do |format|
      if @auto_complete.save
        format.html { redirect_to @auto_complete, notice: 'Auto complete was successfully created.' }
        format.json { render :show, status: :created, location: @auto_complete }
      else
        format.html { render :new }
        format.json { render json: @auto_complete.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /auto_completes/1
  # PATCH/PUT /auto_completes/1.json
  def update
    respond_to do |format|
      if @auto_complete.update(auto_complete_params)
        format.html { redirect_to @auto_complete, notice: 'Auto complete was successfully updated.' }
        format.json { render :show, status: :ok, location: @auto_complete }
      else
        format.html { render :edit }
        format.json { render json: @auto_complete.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /auto_completes/1
  # DELETE /auto_completes/1.json
  def destroy
    @auto_complete.destroy
    respond_to do |format|
      format.html { redirect_to auto_completes_url, notice: 'Auto complete was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search_suggestions
    Product.all
    respond_to do |format|
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_auto_complete
      @auto_complete = AutoComplete.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def auto_complete_params
      params.fetch(:auto_complete, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auto_completes_helper.rb
module AutoCompletesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/auto_completes/_form.html.erb
<%= simple_form_for(@auto_complete) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/auto_completes/edit.html.erb
<h1>Editing Auto Complete</h1>

<%= render 'form', auto_complete: @auto_complete %>

<%= link_to 'Show', @auto_complete %> |
<%= link_to 'Back', auto_completes_path %>

app/views/auto_completes/index.html.erb
<<!-- p id="notice"><%= notice %></p>

<h1>Auto Completes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%# @auto_completes.each do |auto_complete| %>
      <tr>
        <td><%#= link_to 'Show', auto_complete %></td>
        <td><%#= link_to 'Edit', edit_auto_complete_path(auto_complete) %></td>
        <td><%#= link_to 'Destroy', auto_complete, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <%# end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Auto Complete', new_auto_complete_path %>
 -->

<%= form_tag(auto_completes_path, method: "get", remote: true) do %>
  <%= text_field_tag :search_products, params[:search_products], placeholder: "Enter search term" %>
  <%= submit_tag "Search" %>
<% end %>

app/views/auto_completes/index.js.erb
$("#search-results").html("<%= escape_javascript(render :index) %>");

app/views/auto_completes/new.html.erb
<h1>New Auto Complete</h1>

<%= render 'form', auto_complete: @auto_complete %>

<%= link_to 'Back', auto_completes_path %>

app/views/auto_completes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_auto_complete_path(@auto_complete) %> |
<%= link_to 'Back', auto_completes_path %>