config/routes.rb
Rails.application.routes.draw do
  resources :search_suggestions
  root "products#index"
  resources :auto_completes do
    get 'search_suggestions'
  end
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/amount.rb
class Amount < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auto_complete.rb
class AutoComplete < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord

  belongs_to :parent_category, class_name: 'Category', optional: true
end

app/models/color.rb
class Color < ApplicationRecord
end

app/models/currency.rb
class Currency < ApplicationRecord
end

app/models/gender.rb
class Gender < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :vendor, optional: true
  belongs_to :user, optional: true
  belongs_to :product, optional: true
  belongs_to :payable_amount, class_name: "Amount", optional: true
  belongs_to :product_color_mapping, optional: true
  belongs_to :product_size_mapping, optional: true
end

app/models/product.rb
class Product < ApplicationRecord

  has_many :product_secondary_titles, dependent: :destroy
  has_many :product_category_mappings
  has_many :categories, through: :product_category_mappings
  has_many :product_color_mappings
  has_many :colors, through: :product_color_mappings
  has_many :product_vendor_mappings
  has_many :vendors, through: :product_vendor_mappings
  has_many :product_size_mappings
  has_many :sizes, through: :product_size_mappings
end

app/models/product_color_mapping.rb
class ProductColorMapping < ApplicationRecord
  belongs_to :product, optional: true
  belongs_to :color, optional: true
end

app/models/product_gender_mapping.rb
class ProductGenderMapping < ApplicationRecord
  belongs_to :product, optional: true
  belongs_to :gender, optional: true
end

app/models/product_size_mapping.rb
class ProductSizeMapping < ApplicationRecord
  belongs_to :product, optional: true
  belongs_to :size, optional: true
end

app/models/product_sku.rb
class ProductSku < ApplicationRecord
  belongs_to :product, optional: true
  belongs_to :product_category_mapping, optional: true
  belongs_to :product_color_mapping, optional: true
  belongs_to :product_vendor_mapping, optional: true
  belongs_to :product_gender_mapping, optional: true
  belongs_to :product_size_mapping, optional: true
  belongs_to :buyer, class_name: "User", optional: true
end

app/models/search_suggestion.rb
class SearchSuggestion < ApplicationRecord
end

app/models/size.rb
class Size < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/models/vendor.rb
class Vendor < ApplicationRecord
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auto_completes_helper.rb
module AutoCompletesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <%= render 'layouts/navigation_links' %>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<ul class="nav navbar-nav navbar-left">
  <li><%= link_to 'Products', products_path %></li>
  <li id="notifications"> </li>
</ul>
<ul class="nav navbar-nav navbar-right">
 </ul> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Product Search App" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Product Search App" %>">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <div class="container-fluid">
        <%= render 'layouts/messages' %>
        <%= yield %>
      </div>
    </main>
  </body>
</html>